Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using F1Pharmacy.Models;

namespace F1Pharmacy.Controllers;

public class CustomerController : Controller
{
    private readonly F1PharmacyContext _context;

    public CustomerController (F1PharmacyContext context)
    {
        _context = context;
    }

    public IActionResult Index () => View(_context.Customers);

    public IActionResult Show(int id)
    {
        Customer customer = _context.Customers.Find(id);

        if(customer == null)
        {
            return RedirectToAction("Index");
        }

        return View(customer);
    }

    public IActionResult Delete(int id){
        _context.Customers.Remove(_context.Customers.Find(id));
        _context.SaveChanges();
        return View();
    }

    [HttpGet]
    public IActionResult Create(){
                
        return View();
    }

    [HttpPost]
    public IActionResult Create(Customer customer){
        
        if(_context.Customers.Find(customer.Id) != null)
        {
            return Content("Cliente já cadastrado");
        }
        
        _context.Customers.Add(customer);
        _context.SaveChanges();
        return RedirectToAction("Create");
    }

    [HttpGet]
    public IActionResult Update([FromRoute] int id){
        Customer customer = _context.Customers.Find(id);

        if(customer == null)
        {
            return NotFound();
        }

        return View(customer);
    }

    [HttpPost]
    public IActionResult Update(Customer customerUpdated){

        try
        {
            _context.Customers.Update(customerUpdated);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return NotFound();
        }
    }
}



// [FromForm] int id, [FromForm] string name, [FromForm] string city, [FromForm] string address, [FromForm] string email, [FromForm] string phone

Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using F1Pharmacy.Models;

namespace F1Pharmacy.Controllers;

public class SaleController : Controller
{
    private readonly F1PharmacyContext _context;

    public SaleController (F1PharmacyContext context)
    {
        _context = context;
    }

    public IActionResult Index () => View(_context.Sales);

    public IActionResult Show(int id)
    {
        Sale sale = _context.Sales.Find(id);

        if(sale == null)
        {
            return RedirectToAction("Index");
        }

        return View(sale);
    }

    public IActionResult Delete(int id){
        _context.Sales.Remove(_context.Sales.Find(id));
        _context.SaveChanges();
        return View();
    }

    [HttpGet]
    public IActionResult Create(){
                
        return View();
    }

    [HttpPost]
    public IActionResult Create(Sale sale){
        
        if(_context.Sales.Find(sale.Id) != null)
        {
            return Content("Item já cadastrado");
        }
        
        _context.Sales.Add(sale);
        _context.SaveChanges();
        return RedirectToAction("Create");
    }

    [HttpGet]
    public IActionResult Update([FromRoute] int id){
        Sale sale = _context.Sales.Find(id);

        if(sale == null)
        {
            return NotFound();
        }

        return View(sale);
    }

    [HttpPost]
    public IActionResult Update(Sale customerUpdated){
        try
        {
            _context.Sales.Update(customerUpdated);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return NotFound();
        }
    }
}

Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using F1Pharmacy.Models;

namespace F1Pharmacy.Controllers;

public class StockController : Controller
{
    private readonly F1PharmacyContext _context;

    public StockController (F1PharmacyContext context)
    {
        _context = context;
    }

    public IActionResult Index () => View(_context.Stocks);

    public IActionResult Show(int id)
    {
        Stock stock = _context.Stocks.Find(id);

        if(stock == null)
        {
            return RedirectToAction("Index");
        }

        return View(stock);
    }

    public IActionResult Delete(int id){
        _context.Stocks.Remove(_context.Stocks.Find(id));
        _context.SaveChanges();
        return View();
    }

    [HttpGet]
    public IActionResult Create(){
                
        return View();
    }

    [HttpPost]
    public IActionResult Create(Stock stock){
        
        if(_context.Stocks.Find(stock.Id) != null)
        {
            return Content("Item já cadastrado");
        }
        
        _context.Stocks.Add(stock);
        _context.SaveChanges();
        return RedirectToAction("Create");
    }

    [HttpGet]
    public IActionResult Update([FromRoute] int id){
        Stock stock = _context.Stocks.Find(id);

        if(stock == null)
        {
            return NotFound();
        }

        return View(stock);
    }

    [HttpPost]
    public IActionResult Update(Stock customerUpdated){
        try
        {
            _context.Stocks.Update(customerUpdated);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return NotFound();
        }
    }
}

Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using F1Pharmacy.Models;

namespace F1Pharmacy.Controllers;

public class StoreController : Controller
{
    private readonly F1PharmacyContext _context;

    public StoreController(F1PharmacyContext context)
    {
        _context = context;
    }

    public IActionResult Index () => View(_context.Stores);

    public IActionResult Show(int id)
    {
        Store store = _context.Stores.Find(id);

        if(store == null)
        {
            return NotFound(); // RedirectToAction("Index");
        }

        return View(store);
    }

    public IActionResult Create([FromForm] int id, [FromForm] string city, [FromForm] string address, [FromForm] string manager)
    {
        if(_context.Stores.Find(id) == null)
        {
            Store store = new Store(id,city,address,manager);
            _context.Stores.Add(store);
            _context.SaveChanges();
            return View("Cadastro");
        }
        else
        {
           return Content("Uma loja com esse ID já foi cadastrado, por favor insira outro ID.");
        }
    }

    public IActionResult Cadastro()
    {
        return View();
    }

     public IActionResult Delete(int id){

        Store unity = _context.Stores.Find(id);
        _context.Stores.Remove(unity);
        _context.SaveChanges();

        return View();
    }

    [HttpGet]
    public IActionResult Update([FromRoute] int id){
        Store store = _context.Stores.Find(id);

        if(store == null)
        {
            return NotFound();
        }

        return View(store);
    }

    [HttpPost]
    public IActionResult Update(int id, [FromForm] string city, [FromForm] string address, [FromForm] string manager){
        Store store = _context.Stores.Find(id);

        if(store == null)
        {
            return Content("A loja não existe");
        }
        else
        {
            store.Id = id;
            store.City = city;
            store.Address = address;
            store.Manager = manager;
            _context.Stores.Update(store);
            _context.SaveChanges();
            return Content("Especificações da loja atualizadas com sucesso!");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - F1Pharmacy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/F1Pharmacy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">F1Pharmacy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicines</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index">Stock</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Sale</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - F1Pharmacy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>