Models/Medicine.cs
namespace F1Pharmacy.Models;

public class Medicine
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Type { get; set; }
    public string Description { get; set; }

    public Medicine() {}

    public Medicine(int id, string name, string type, string description)
    {
        Id = id;
        Name = name;
        Type = type;
        Description = description;
    }
}

Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using F1Pharmacy.Models;

namespace F1Pharmacy.Controllers;

public class MedicineController : Controller
{
    private readonly F1PharmacyContext _context;

    public MedicineController(F1PharmacyContext context)
    {
        _context = context;
    }

    public IActionResult Index () => View(_context.Medicines);

    public IActionResult Show(int id)
    {
        Medicine medicine = _context.Medicines.Find(id);

        if(medicine == null)
        {
            return NotFound(); // RedirectToAction("Index");
        }

        return View(medicine);
    }

    public IActionResult Create([FromForm] int id, [FromForm] string name, [FromForm] string type, [FromForm] string description)
    {
        if(_context.Stores.Find(id) == null)
        {
            Medicine medicine = new Medicine(id,name,type,description);
            _context.Medicines.Add(medicine);
            _context.SaveChanges();
            return View("Cadastro");
        }
        else
        {
           return Content("Um medicamento com esse ID já foi cadastrado, por favor insira outro ID.");
        }
    }

    public IActionResult Cadastro()
    {
        return View();
    }

     public IActionResult Delete(int id){

        Medicine medicine = _context.Medicines.Find(id);
        _context.Medicines.Remove(medicine);
        _context.SaveChanges();

        return View();
    }



    [HttpGet]
    public IActionResult Update([FromRoute] int id){
        
        Medicine medicine = _context.Medicines.Find(id);

        if(medicine == null)
        {
            return NotFound();
        }

        return View(medicine);
    }

    [HttpPost]
    public IActionResult Update(int id, [FromForm] string name, [FromForm] string type, [FromForm] string description){

        Medicine medicine = _context.Medicines.Find(id);

        if(medicine == null)
        {
            return Content("O medicamento não existe");
        }
        else
        {
            medicine.Id = id;
            medicine.Name = name;
            medicine.Type = type;
            medicine.Description = description;
            _context.Medicines.Update(medicine);
            _context.SaveChanges();
            return Content("Especificações do medicamento atualizadas com sucesso!");
        }
    }
}

Views/Medicine/Cadastro.cshtml
@{

    ViewData["Title"] = "Cadastro";

}

<div class="text-center">
    <h1 class="display-4">Cadastrar medicamento</h1>
</div>

<div class="container">
    <div class="con">
        <div class="right-side">
            <br>
            <form action="Create" method="POST">
                <div class="form-group">
                    <label for="id">Id</label>
                    <input type="text" name="id" id="id" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" name="name" id="name" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="type">Tipo</label>
                    <select class="form-control" name="type" id="type" required>
                        <option value="" disabled selected>Selecione o tipo do medicamento</option>
                        <option value="1">Líquido</option>
                        <option value="2">Comprimido</option>
                        <option value="3">Capsula</option> 
                        <option value="4">Pomada</option>
                        <option value="5">Inalável</option> 
                        <option value="6">Spray</option> 
                        <option value="7">Injeção</option>                         
                    </select>
                </div>
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <input type="text" name="description" id="description" class="form-control" required>
                </div>

                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>

Views/Medicine/Delete.cshtml
@{
    ViewData["Title"] = "Deletar medicamento";
    var id = ViewData["id"];
}

<div class="text-center">
    <h1 class="display-4">O medicamento @id foi deletado com sucesso!</h1>
   
</div>

Views/Medicine/Index.cshtml
@model IEnumerable<F1Pharmacy.Models.Medicine>

@{
    ViewData["Title"] = "Medications";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum medicamento cadastrado</p>
     <p><a class="asd" asp-area="" asp-controller="Medicine" asp-action="Cadastro"><strong>Cadastrar medicamento</strong></a></p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Tipo</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <body>
            @foreach(var medicine in Model)
            {
                <tr>
                    <td>@medicine.Id</td>
                    <td>@medicine.Name</td>
                    <td>@medicine.Type</td>
                    <td>@medicine.Description</td>
                    <td>
                        <a class = "btn btn-primary btn-sm"href ="/Medicine/Show/@medicine.Id">Ver</a>
                        <a class = "btn btn-primary btn-sm"href ="/Medicine/Update/@medicine.Id">Atualizar</a>
                        <a class = "btn btn-primary btn-sm"href ="/Medicine/Delete/@medicine.Id">Deletar</a>
                    </td>
                </tr>
            }
        </body>
    </table>
                
}

Views/Medicine/Show.cshtml
@model F1Pharmacy.Models.Medicine

@{
    ViewData["Title"] = $"Medicamento {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p>
    <b>Id:</b> @Model.Id
</p>
<p>
    <b>Nome:</b> @Model.Name
</p>
<p>
    <b>Tipo:</b> @Model.Type
</p>
<p>
    <b>Descrição:</b> @Model.Description
</p>

Views/Medicine/Update.cshtml
@model F1Pharmacy.Models.Medicine

@{
    ViewData["Title"] = "Atualizar medicamento";
}

<div class="text">
    <h1 class="display-4">Atualizar especificações de medicamento</h1>
    <hr>

</div>
<div class="container">
    <form action="Atualizar" method="POST">
        <div class="form-group">
            <label for="id">Id</label>
            <input type="text" name="id" id="id" class="form-control" value="@Model.Id" readonly>
        </div>
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" name="name" id="name" class="form-control" value="@Model.Name" required>
        </div>
        <div class="form-group">
            <label for="type">Tipo</label>
            <select class="form-control" name="type" id="type" value="@Model.Type" required>
                <option value="" disabled selected>Selecione o tipo do medicamento</option>
                <option value="1">Líquido</option>
                <option value="2">Comprimido</option>
                <option value="3">Capsula</option>
                <option value="4">Pomada</option>
                <option value="5">Inalável</option>
                <option value="6">Spray</option>
                <option value="7">Injeção</option>
            </select>
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <input type="text" name="description" id="description" class="form-control" value="@Model.Description"
                required>
        </div>

        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>